---
- name: Install neovim and dependencies
  ansible.builtin.package:
    name:
      - neovim
      - figlet
      - yarn
      - nodejs

- name: Download the larry3d font (for startify splash screen)
  ansible.builtin.get_url:
    url: https://github.com/xero/figlet-fonts/raw/master/larry3d.flf
    dest: "{{ nvim.prefix.figlet }}/larry3d.flf"
    mode: 0644

- name: Deploy the nvim configuration files
  ansible.posix.synchronize:
    src: files/
    dest: "{{ ansible_env.HOME }}/.config/nvim/"
    delete: true

- name: Check if vim-plug is installed
  register: nvim_vim_plug
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"

- name: Create the vim-plug folders
  loop:
    - ".local"
    - ".local/share"
    - ".local/share/nvim"
    - ".local/share/nvim/site"
    - ".local/share/nvim/site/autoload"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ username }}"
    state: directory
    mode: "0755"


- name: Download and install vim-plug
  when: not nvim_vim_plug.stat.exists
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
    owner: "{{ username }}"
    mode: "0644"

- name: Install and update nvim plugins
  changed_when: no
  ansible.builtin.command:
    cmd: nvim -c "PlugInstall" -c "PlugUprade" -c "PlugUpdate" -c "qa"
